SicoInacap/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SicoInacap.Models;

namespace SicoInacap.Controllers
{

    public class AgendaController : Controller
    {
        private SicoModel db = new SicoModel();

        // GET: Agenda
        public ActionResult Index()
        {
            var agenda = db.Agenda.Include(a => a.Evento).Include(a => a.Recinto);
            return View(agenda.ToList());
        }

        // GET: Agenda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // GET: Agenda/Calendario
        public ActionResult Calendario()
        {

            try
            {
                string recintoId = Request.QueryString["recintoId"];
                ViewBag.CodigoRecinto = new SelectList(db.Recinto, "Codigo", "Nombre", int.Parse(recintoId));
            }
            catch (Exception ex)
            {
                ViewBag.CodigoRecinto = new SelectList(db.Recinto, "Codigo", "Nombre");
            }

            ViewBag.CodigoEvento = new SelectList(db.Evento.Where(e => e.EstadoEvento.Codigo == 1).ToList(), "Codigo", "Descripcion");
            ViewBag.NuevoCodigoRecinto = new SelectList(db.Recinto, "Codigo", "Nombre");
            ViewBag.HoraInicio = new SelectList(db.Bloque, "HoraInicio", "HoraInicio");
            return View();
        }

        // GET: Agenda/Create
        public ActionResult Create()
        {
            ViewBag.CodigoEvento = new SelectList(db.Evento, "Codigo", "Descripcion");
            ViewBag.CodigoRecinto = new SelectList(db.Recinto, "Codigo", "Nombre");
            ViewBag.HoraInicio = new SelectList(db.Bloque, "HoraInicio", "HoraInicio");
            return View();
        }

        public JsonResult GetAgenda()
        {
            string recintoId = Request.QueryString["recintoId"];
            List<Object> list = new List<object>();
            foreach (Agenda item in db.Agenda.ToList<Agenda>())
                if (item.CodigoRecinto.ToString().Equals(recintoId))
                    list.Add(new
                    {
                        id = item.Evento.Codigo,
                        title = item.Evento.Nombre,
                        description = item.Evento.Descripcion,
                        start = item.HoraInicio.Year + "-" + item.HoraInicio.Month + "-" + item.HoraInicio.Day + " " + item.HoraInicio.Hour + ":00:00",
                        end = item.HoraTermino.Year + "-" + item.HoraTermino.Month + "-" + item.HoraTermino.Day + " " + item.HoraTermino.Hour + ":00:00",
                        color = "#01579b"
                    });
            return new JsonResult { Data = list, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        private void UpdateAgendaBloques(Agenda agenda)
        {
            DateTime fechaInicio = new DateTime(agenda.HoraInicio.Year, agenda.HoraInicio.Month, agenda.HoraInicio.Day);
            DateTime fechaFin = new DateTime(agenda.HoraTermino.Year, agenda.HoraTermino.Month, agenda.HoraTermino.Day);
            for (DateTime fecha = fechaInicio; fecha <= fechaFin; fecha = fecha.AddDays(1))
            {
                int horaInicio = fecha.Day.Equals(agenda.HoraInicio.Day) && fecha.Month.Equals(agenda.HoraInicio.Month) && fecha.Year.Equals(agenda.HoraInicio.Year) ? agenda.HoraInicio.Hour : 0;
                int horaFin = fecha.Day.Equals(agenda.HoraTermino.Day) && fecha.Month.Equals(agenda.HoraTermino.Month) && fecha.Year.Equals(agenda.HoraTermino.Year) ? agenda.HoraTermino.Hour : 0;
                if (horaFin.Equals(0) && fecha.Equals(fechaFin))
                    break;
                this.GetRange(horaInicio, horaFin).ForEach(bloque => db.AgendaBloque.Add(new AgendaBloque { Agenda = agenda, CodigoAgenda = (int)agenda.Codigo, Bloque = bloque, CodigoBloque = bloque.Codigo, Fecha = fecha }));
            }
            db.SaveChanges();
        }

        private List<Bloque> GetRange(int start, int end)
        {
            return start == 0 && end == 0 ? db.Bloque.ToList() : db.Bloque.Where(b => b.HoraInicio.Hours >= start && (b.HoraInicio.Hours < end || end == 0)).ToList();
        }

        public JsonResult SaveAgenda([Bind(Include = "CodigoEvento,CodigoRecinto,HoraInicio,HoraTermino")] Agenda agenda)
        {
            try
            {
                List<Agenda> list = db.Agenda.Where(a => a.Evento.Codigo.Equals(agenda.CodigoEvento)).ToList();
                if (list.Count > 0 && list.First().Evento.CodigoEstado == 2)
                {
                    Agenda original = db.Agenda.Find(list.First().Codigo);
                    original.Recinto = db.Recinto.Find(agenda.CodigoRecinto);
                    original.CodigoRecinto = agenda.CodigoRecinto;
                    original.HoraInicio = agenda.HoraInicio;
                    original.HoraTermino = agenda.HoraTermino;
                    if (db.SaveChanges() > 0)
                    {
                        List<AgendaBloque> lst = new List<AgendaBloque>();
                        foreach (AgendaBloque item in db.AgendaBloque.ToList())
                            if (item.CodigoAgenda.Equals(original.Codigo))
                                lst.Add(item);
                        lst.ForEach(ab => db.AgendaBloque.Remove(ab));
                        this.UpdateAgendaBloques(original);
                    }
                }
                else
                {
                    agenda.Evento = db.Evento.Find(agenda.CodigoEvento);
                    agenda.Recinto = db.Recinto.Find(agenda.CodigoRecinto);
                    db.Agenda.Add(agenda);

                    if (db.SaveChanges() > 0)
                    {
                        db.Evento.Find(agenda.Evento.Codigo).EstadoEvento = db.EstadoEvento.Find(2);
                        if (db.SaveChanges() > 0)
                            this.UpdateAgendaBloques(agenda);
                    }
                }

                return new JsonResult { Data = agenda.CodigoRecinto, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
            catch(Exception ex)
            {
                return new JsonResult { Data = ex.Message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        // POST: Agenda/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Codigo,CodigoEvento,CodigoRecinto,HoraInicio,HoraTermino")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Agenda.Add(agenda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CodigoEvento = new SelectList(db.Evento, "Codigo", "Descripcion", agenda.CodigoEvento);
            ViewBag.CodigoRecinto = new SelectList(db.Recinto, "Codigo", "Latitud", agenda.CodigoRecinto);
            return View(agenda);
        }

        // GET: Agenda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.CodigoEvento = new SelectList(db.Evento, "Codigo", "Descripcion", agenda.CodigoEvento);
            ViewBag.CodigoRecinto = new SelectList(db.Recinto, "Codigo", "Latitud", agenda.CodigoRecinto);
            return View(agenda);
        }

        // POST: Agenda/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Codigo,CodigoEvento,CodigoRecinto,HoraInicio,HoraTermino")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CodigoEvento = new SelectList(db.Evento, "Codigo", "Descripcion", agenda.CodigoEvento);
            ViewBag.CodigoRecinto = new SelectList(db.Recinto, "Codigo", "Latitud", agenda.CodigoRecinto);
            return View(agenda);
        }

        // GET: Agenda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // POST: Agenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Agenda agenda = db.Agenda.Find(id);
            db.Agenda.Remove(agenda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

SicoInacap/Controllers/RecintosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SicoInacap.Models;

namespace SicoInacap.Controllers
{
    public class RecintosController : Controller
    {
        private SicoModel db = new SicoModel();

        // GET: Recintoes
        public ActionResult Index()
        {
            return View(db.Recinto.ToList());
        }

        // GET: Recintoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recinto recinto = db.Recinto.Find(id);
            if (recinto == null)
            {
                return HttpNotFound();
            }
            return View(recinto);
        }

        // GET: Recintoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recintoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Latitud,Longitud,Nombre")] Recinto recinto)
        {
            if (ModelState.IsValid)
            {
                db.Recinto.Add(recinto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(recinto);
        }

        // GET: Recintoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recinto recinto = db.Recinto.Find(id);
            if (recinto == null)
            {
                return HttpNotFound();
            }
            return View(recinto);
        }

        // POST: Recintoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Codigo,Latitud,Longitud,Nombre")] Recinto recinto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recinto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recinto);
        }

        // GET: Recintoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recinto recinto = db.Recinto.Find(id);
            if (recinto == null)
            {
                return HttpNotFound();
            }
            return View(recinto);
        }

        // POST: Recintoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recinto recinto = db.Recinto.Find(id);
            db.Recinto.Remove(recinto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SicoInacap/Views/Shared/_Layout.cshtml
@{
    if (Session["username"] == null)
    {
        Response.Redirect("~/Login/index");
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/material-dashboard.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto mx-3">
                    <li class="nav-item ">
                        @Html.ActionLink("Inicio", "Index", "Home", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Gestion de Usuarios", "Index", "Usuarios", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Gestion de Agenda", "Index", "Agenda", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Gestion de Eventos", "Index", "Evento", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Gestion de Recintos", "Index", "Recintos", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Bloques", "Index", "Bloques", null, new { @class = "nav-link" })
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    </div>

    <div class="container">
        @RenderBody()


    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!--
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>


        -->
    <script src="~/Scripts/sweetalert2.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8-xszb_U0t3DlkGRnWFp3vigBKbML7XE&callback=inicializacion" async defer>

    </script>

    <script>
        $('#myModal').on('shown.bs.modal', function () {
            $('#myInput').trigger('focus')
        })
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

SicoInacap/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/login.css" rel="stylesheet" />
</head>
<body id="LoginForm">
    
    <div class="container">
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        @RenderBody()


    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>