SicoInacap/Models/Evento.cs
namespace SicoInacap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Evento")]
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            Agenda = new HashSet<Agenda>();
            Usuario = new HashSet<Usuario>();
            Usuario1 = new HashSet<Usuario>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Codigo { get; set; }
        public int CodigoCategoria { get; set; }

        public int CodigoEstado { get; set; }

        [Required]
        public string Descripcion { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        [StringLength(50)]
        public string UsernameOrganizador { get; set; }

        [StringLength(50)]
        public string UsernameResponsable { get; set; }

        public virtual Administrador Administrador { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }

        public virtual Categoria Categoria { get; set; }

        public virtual EstadoEvento EstadoEvento { get; set; }

        public virtual Miembro Miembro { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario1 { get; set; }
    }
}

SicoInacap/Controllers/eventoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SicoInacap.Models;

namespace SicoInacap.Controllers
{
    public class eventoController : Controller
    {
        private SicoModel db = new SicoModel();

        // GET: evento
        public ActionResult Index()
        {
            var evento = db.Evento.Include(e => e.Administrador).Include(e => e.Categoria).Include(e => e.EstadoEvento).Include(e => e.Miembro);
            return View(evento.ToList());
        }

        // GET: evento/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Evento.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // GET: evento/Create
        public ActionResult Create()
        {
            ViewBag.UsernameOrganizador = new SelectList(db.Administrador, "Username", "Username");
            ViewBag.CodigoCategoria = new SelectList(db.Categoria, "Codigo", "Nombre");
            ViewBag.CodigoEstado = new SelectList(db.EstadoEvento, "Codigo", "Nombre");
            ViewBag.UsernameResponsable = new SelectList(db.Simpatizante.Where(simpatizante => db.Miembro.Any(miembro => miembro.Username == simpatizante.Username)), "Username", "Nombres");
            return View();
        }

        // POST: evento/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodigoCategoria,CodigoEstado,Descripcion,Nombre,UsernameOrganizador,UsernameResponsable")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                db.Evento.Add(evento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UsernameOrganizador = new SelectList(db.Administrador, "Username", "Username", evento.UsernameOrganizador);
            ViewBag.CodigoCategoria = new SelectList(db.Categoria, "Codigo", "Nombre", evento.CodigoCategoria);
            ViewBag.CodigoEstado = new SelectList(db.EstadoEvento, "Codigo", "Nombre", evento.CodigoEstado);
            ViewBag.UsernameResponsable = new SelectList(db.Simpatizante.Where(simpatizante => db.Miembro.Any(miembro => miembro.Username == simpatizante.Username)), "Username", "Nombres", evento.UsernameResponsable);
            return View(evento);
        }

        // GET: evento/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Evento.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            ViewBag.UsernameOrganizador = new SelectList(db.Administrador, "Username", "Username", evento.UsernameOrganizador);
            ViewBag.CodigoCategoria = new SelectList(db.Categoria, "Codigo", "Nombre", evento.CodigoCategoria);
            ViewBag.CodigoEstado = new SelectList(db.EstadoEvento, "Codigo", "Nombre", evento.CodigoEstado);
            ViewBag.UsernameResponsable = new SelectList(db.Simpatizante.Where(simpatizante => db.Miembro.Any(miembro => miembro.Username == simpatizante.Username)), "Username", "Nombres", evento.UsernameResponsable);
            return View(evento);
        }

        // POST: evento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Codigo,CodigoCategoria,CodigoEstado,Descripcion,Nombre,UsernameOrganizador,UsernameResponsable")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UsernameOrganizador = new SelectList(db.Administrador, "Username", "Username", evento.UsernameOrganizador);
            ViewBag.CodigoCategoria = new SelectList(db.Categoria, "Codigo", "Nombre", evento.CodigoCategoria);
            ViewBag.CodigoEstado = new SelectList(db.EstadoEvento, "Codigo", "Nombre", evento.CodigoEstado);
            ViewBag.UsernameResponsable = new SelectList(db.Simpatizante.Where(simpatizante => db.Miembro.Any(miembro => miembro.Username == simpatizante.Username)), "Username", "Nombres", evento.UsernameResponsable);
            return View(evento);
        }

        // GET: evento/Delete/5
        public ActionResult Delete(int? id, bool? error = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Evento.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            ViewBag.error = error;
            return View(evento);
        }

        // POST: evento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try {
                Evento evento = db.Evento.Find(id);
                db.Evento.Remove(evento);
                db.SaveChanges();
            }
            catch (Exception e) {
                
                return RedirectToAction("Delete", new { id = id, error = true });
            }
            return RedirectToAction("Index");
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SicoInacap/Views/evento/Create.cshtml
@model SicoInacap.Models.Evento

@{
    ViewBag.Title = "Crear evento";
}
<nav aria-label="breadcrumb" class="mt-2">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">@Html.ActionLink("Gestion de Eventos", "Index", "evento")</li>
        <li class="breadcrumb-item active">Crear Recinto</li>
    </ol>
</nav>

<span class="badge badge-pill badge-success mb-2">
    @Html.ActionLink("Regresar", "Index", null, new { @class = "nav-link text-light" })
</span>

<div class="card">
    <div class="card-header card-header-rose text-center">
        <h4 class="card-title">Ingrese los Datos del Nuevo Evento</h4>
    </div>
    <div class="card-body table-responsive">
        @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group d-none">
                @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CodigoCategoria, "CodigoCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.DropDownList("CodigoCategoria", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodigoCategoria, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CodigoEstado, "CodigoEstado", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.DropDownList("CodigoEstado", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodigoEstado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UsernameOrganizador, "UsernameOrganizador", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.DropDownList("UsernameOrganizador", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UsernameOrganizador, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UsernameResponsable, "UsernameResponsable", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.DropDownList("UsernameResponsable", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UsernameResponsable, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <input type="submit" value="Crear" class="btn btn-primary btn-lg btn-block" />
                </div>
            </div>
        </div>
}

    </div>
</div>






@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SicoInacap/Views/evento/Delete.cshtml
@model SicoInacap.Models.Evento

@{
    ViewBag.Title = "Eliminar evento";
}
<nav aria-label="breadcrumb" class="mt-2">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">@Html.ActionLink("Gestion de Eventos", "Index", "evento")</li>
        <li class="breadcrumb-item active">Borrar Evento</li>
    </ol>
</nav>

<span class="badge badge-pill badge-success mb-2">
    @Html.ActionLink("Regresar", "Index", null, new { @class = "nav-link text-light" })
</span>


<div class="card">
    <div class="card-header card-header-primary text-center">
        <h4 class="card-title">Evento a Eliminar</h4>
    </div>
    <div class="card-body table-responsive">
        <table class="table bg-dark text-light rounded">
            <thead class="text-primary text-center">
                <tr>
                    <th>
                        Encargado
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Categoria.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EstadoEvento.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Miembro.Fono)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Descripcion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                   
                </tr>
            </thead>
            <tbody class="text-center">
               
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Administrador.Username)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Categoria.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(model => model.EstadoEvento.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Miembro.Fono)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Nombre)
                </td>
                
            </tr>

            </tbody>
        </table>
        <div class="form-actions no-color">
            <input type="button" value="Borrar" class="btn btn-danger btn-lg btn-block" data-toggle="modal" data-target="#exampleModalCenter" />

        </div>
    </div>
</div>





<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Borrar Evento</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Esta Seguro de Borrar este Evento?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Aceptar" class="btn btn-success" />
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(() => {
            @if(ViewBag.error)
            {
                @:swal("Eliminación Cancelada", "No se puede eliminar el evento, puesto que ya se encuentra agendado","error")
            }
        });

    </script>
}

SicoInacap/Views/evento/Details.cshtml
@model SicoInacap.Models.Evento

@{
    ViewBag.Title = "Details";
}

<!-- Migas de pan -->
<nav aria-label="breadcrumb" class="mt-2 mb-5">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">@Html.ActionLink("Gestion de Eventos", "Index", "evento", null)</li>
        <li class="breadcrumb-item active">Detalles del Personal</li>
    </ol>
</nav>

<!-- /Migas de pan -->


<div class="col-md-12" style="margin-top:80px;">
    <div class="card card-profile">
        <div class="card-avatar bg-dark">
            <img src="~/img/evento.png" />
        </div>
        <div class="card-body">
            <h5 class="card-category text-gray">@Html.DisplayFor(model => model.Nombre)</h5>
            <h6 class="card-title">Encargado: @Html.DisplayFor(model => model.Administrador.Username)</h6>
            <h6 class="card-title">Categoria: @Html.DisplayFor(model => model.Categoria.Nombre)</h6>
            <h6 class="card-title">Estado: @Html.DisplayFor(model => model.EstadoEvento.Nombre)</h6>
            <p class="card-description">
                @Html.DisplayFor(model => model.Descripcion)
            </p>

            <!-- Boton Regresar -->
            <span class="badge badge-pill badge-success mb-2">
                @Html.ActionLink("Regresar", "Index", null, new { @class = "nav-link text-light" })
            </span>
            <!-- /Boton Regresar -->
        </div>
    </div>
</div>

SicoInacap/Views/evento/Edit.cshtml
@model SicoInacap.Models.Evento

@{
    ViewBag.Title = "Editar mevento";
}

<nav aria-label="breadcrumb" class="mt-2">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">@Html.ActionLink("Gestion de Eventos", "Index", "evento")</li>
        <li class="breadcrumb-item active">Modificar Recinto</li>
    </ol>
</nav>

<span class="badge badge-pill badge-success mb-2">
    @Html.ActionLink("Regresar", "Index", null, new { @class = "nav-link text-light" })
</span>

<div class="card">
    <div class="card-header card-header-rose text-center">
        <h4 class="card-title">Ingrese los Datos a Modificar del Evento</h4>
    </div>
    <div class="card-body table-responsive">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group d-none">
                    @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CodigoCategoria, "CodigoCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.DropDownList("CodigoCategoria", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CodigoCategoria, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CodigoEstado, "CodigoEstado", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.DropDownList("CodigoEstado", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CodigoEstado, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UsernameOrganizador, "UsernameOrganizador", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.DropDownList("UsernameOrganizador", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UsernameOrganizador, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UsernameResponsable, "UsernameResponsable", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.DropDownList("UsernameResponsable", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UsernameResponsable, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-12">
                        <input type="submit" value="Modificar" class="btn btn-warning btn-lg btn-block" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SicoInacap/Views/evento/Index.cshtml
@model IEnumerable<SicoInacap.Models.Evento>

@{
    ViewBag.Title = "Index";
}



<nav aria-label="breadcrumb" class="mt-2">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">@Html.ActionLink("Gestion de Eventos", "Index", "evento", null)</li>
    </ol>
</nav>
<span class="label label-success">

</span>

<span class="badge badge-pill badge-primary mb-2">
    @Html.ActionLink("Crear Nuevo Evento", "Create", null, new { @class = "nav-link text-light" })
</span>


<div class="card">
    <div class="card-header card-header-success text-center">
        <h4 class="card-title">Nuestros Eventos</h4>
    </div>
    <div class="card-body table-responsive">
        <table class="table bg-dark text-light rounded">
            <thead class="text-primary text-center">
                <tr>
                    <th>
                        Encargado
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Categoria.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EstadoEvento.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Miembro.Fono)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Descripcion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                    <th>
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody class="text-center">
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Administrador.Username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Categoria.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EstadoEvento.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Miembro.Fono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td class="td-actions text-center">
                        <a href="@Url.Action("Edit", "evento",new { id = item.Codigo })" class="btn btn-warning">
                            <i class="material-icons">edit</i>
                            <span>
                                <strong>Editar</strong>
                            </span>
                        </a>
                        <a href="@Url.Action("Details", "evento",new { id = item.Codigo })" class="btn btn-info">
                            <i class="material-icons">recent_actors</i>
                            <span>
                                <strong>Detalles</strong>
                            </span>
                        </a>
                        <a href="@Url.Action("Delete", "evento",new { id = item.Codigo })" class="btn btn-danger">
                            <i class="material-icons">delete_sweep</i>
                            <span>
                                <strong>Eliminar</strong>
                            </span>
                        </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>